### ISSUE TITLE
Cursor not being locked on extended display/2 monitors

### ISSUE THREAD

**Issue by FACS01-01** [RequiDev/CursorLockFix#1]
In VRChat, when I open the Quick Menu and rotate the view, my cursor can go to my second monitor. And if I do any click there, VRC window loses focus.

**Comment by RequiDev** [comment]
What's your monitor setup? I have monitors in every direction of the window and it works fine.  Are you using the latest version?

**Comment by FACS01-01** [comment]
I'm playing on a laptop as Desktop(Non VR) so I have its display as my main one on which I run the game, and also have a second extended display on HDMI. The first one uses AMD integrated GPU and the second one uses dedicated GPU (RTX3060). The game is using the RTX GPU of course.
I just downloaded the mod to be sure.

Doing some more testing, I discovered that the bug happens when opening the game directly with the VRChat executable (as I usually do), or on Steam when selecting "Launch on SteamVR mode", and doesn't happen when on Steam selecting "Launch on Desktop mode".

**Comment by RequiDev** [comment]
Weird. It should be checking whether an XRDevice is present or not. It definitely only works on Desktop mode, that's for sure. Otherwise, VR overlays get stuck in the VRChat window.

**Comment by FACS01-01** [comment]
I don't have any VR device so idk.
Can it be fixed for when opening the game directly with the .exe? I prefer not having Steam open hahah.

**Comment by RequiDev** [comment]
Use a shortcut to add the launch parameter "--no-vr". That should make it work.

**Comment by FACS01-01** [comment]
It does!! Thanks!
